# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXd_ocK17QV9cGqZHT9EYYtvK-ONGnFu
"""



print("These are Yes or No Questions.")
print("It means that you can only answer with Yes or No")
age= str(input("Are you a cigarette addict older than 75 years old?"))
chronic = str(input("Do you have a severe chronic disease?"))
immune= str(input("Is your immune system too weak? "))
cevap = ("Yes","No")
No=("No")
if age not in cevap:
  print("You can only response with Yes or No" + " The Answer will incorrect")
if age in No:
  age=None
if chronic not in cevap:
  print("You can only response with Yes or No" + " The Answer will incorrect")
if chronic in No:
  chronic=None
if immune not in cevap:
  print("You can only response with Yes or No" + " The Answer will incorrect")
if immune in No:
  immune=None
sonuc= bool(age or chronic or immune)
print(sonuc)
if sonuc:
  print ("You are in risky group")
else:
  print("You are not in risky group")

bool(None)